### ISSUE TITLE
Security: create email for Phone Buddies application

### ISSUE THREAD

**Issue by J99eow** [mokolodi1/aesop-afghanistan#7]
Adding a Google email address that has access to the PB database that is separate from the main AESOP email, and therefore reduces the number of people who have access to changing the PB application.

**Comment by mokolodi1** [comment]
Created the new email: https://github.com/mokolodi1/aesop-afghanistan/commit/cabf6a95a87bf7264cf7f3ca62f5767f21e997de

Deployed to prod and tested with a trial email. It's coming from the right email!
